=== Getting Started

The plugin can be applied with the `buildscript` syntax or the plugin DSL.
Let's say you'd want to go with the plugin that provides the plain Docker operations for managing Docker images and containers.
See the {uri-gradle-docs}/userguide/plugins.html[Gradle user guide] for more information on applying plugins.

==== Applying the Plugin Using the buildscript Syntax

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::{samplesCodeDir}/remote-api-plugin/apply-plugin-buildscript/groovy/build.gradle[]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::{samplesCodeDir}/remote-api-plugin/apply-plugin-buildscript/kotlin/build.gradle.kts[]
----

==== Applying the Plugin Using the Plugin DSL

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::{samplesCodeDir}/remote-api-plugin/apply-plugin-dsl/groovy/build.gradle[]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::{samplesCodeDir}/remote-api-plugin/apply-plugin-dsl/kotlin/build.gradle.kts[]
----

[IMPORTANT]
Using the `plugins {}` block to apply the plugin requires special handling in a multi-project build. For more information, see the Gradle documentation section named {uri-gradle-docs}/userguide/plugins.html#sec:subprojects_plugins_dsl["Applying external plugins with same version to subprojects"].

==== Applying the Plugin From a Script Plugin

Applying the plugin from a script plugin requires the use of the fully-qualified class name due to a https://github.com/gradle/gradle/issues/1262[bug in Gradle core]. Be aware that the plugin DSL cannot be used to apply a binary plugin from a script plugin.

[NOTE]
When used with the Kotlin DSL, it is recommended to move your implementation into the `buildSrc` project.

.gradle/docker.gradle
[source,groovy,subs="+attributes"]
----
include::{samplesCodeDir}/remote-api-plugin/apply-plugin-from-script-plugin/groovy/gradle/docker.gradle[]
----

.build.gradle
[source,groovy,subs="+attributes"]
----
include::{samplesCodeDir}/remote-api-plugin/apply-plugin-from-script-plugin/groovy/build.gradle[]
----