=== Extension

The plugin defines an extension with the namespace `docker`.
The following properties can be configured:

[options="header"]
|=======
|Property name      |Type                |Default value              |Description
|`url`              |`Property<String>`  |see below                  |The server URL to connect to via Docker's remote API.
|`certPath`         |`DirectoryProperty` |`null`                     |The path to certificates for communicating with https://docs.docker.com/articles/https/[Docker over SSL].
|`Property<String>` |`String`            |`null`                     |The remote API version. For most cases this can be left null.
|=======

The default value is now generated based on a best guess attempt given the https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/DockerExtension.groovy#L42[operating system and environment]:

[options="header"]
|=======
|Operating system                            | Value
|Unix-based machine                          | `unix:///var/run/docker.sock`
|Windows-based machine (and everything else) | `tcp://127.0.0.1:2375`
|=======

Image pull or push operations against the public Docker Hub registry or a private registry may require authentication.
You can provide those credentials in the `registryCredentials` closure:

[options="header"]
|=======
|Property name   |Type                  |Default value                 |Description
|`url`           |`Property<String>`    |`https://index.docker.io/v1/` |The registry URL.
|`username`      |`Property<String>`    |`null`                        |The registry username.
|`password`      |`Property<String>`    |`null`                        |The registry password.
|`email`         |`Property<String>`    |`null`                        |The registry email address.
|=======

==== Working With a TLS-enabled Docker Instance

Starting with Docker version 1.3, TLS is enabled by default.
Please consult the Docker documentation https://docs.docker.com/engine/security/https/["Protect the Docker daemon socket"] to set up your certificate. The following example demonstrates how to configure the plugin to use those certificates.
Additionally, this code snippet shows how to set the user credentials.

.build.gradle
[source,groovy,subs="+attributes"]
----
docker {
    url = 'https://192.168.59.103:2376'
    certPath = new File(System.properties['user.home'], '.boot2docker/certs/boot2docker-vm')

    registryCredentials {
        url = 'https://index.docker.io/v1/'
        username = 'bmuschko'
        password = 'pwd'
        email = 'benjamin.muschko@gmail.com'
    }
}
----

==== Working With Google Cloud And Using a Key File

.build.gradle
[source,groovy,subs="+attributes"]
----
docker {
    registryCredentials {
        url = 'https://gcr.io'
        username = '_json_key'
        password = file('keyfile.json").text
    }
}
----

==== Working With a Docker Instance Without TLS

The following example assumes that you disabled TLS on your Docker instance.
You can do so by setting `DOCKER_TLS=no` in the file `/var/lib/boot2docker/profile`.

.build.gradle
[source,groovy,subs="+attributes"]
----
docker {
    url = 'tcp://192.168.59.103:2375'
}
----

On Unix the Docker daemon listens by default on `unix:///var/run/docker.sock`.

On Windows the Docker daemon listens by default on `npipe:////./pipe/docker_engine` though this is not currently supported.
We instead fall back to `tcp://127.0.0.1:2375`.