=== Examples

The following usage examples demonstrate code for common use cases.
More scenarios can be found in the {uri-github}/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/DockerWorkflowFunctionalTest.groovy[functional tests].

==== Creating a Dockerfile And Building an Image

A Dockerfile can be created by the `Dockerfile` custom tasks.
The Dockerfile instructions need to be declare in the correct
order.

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::{samplesCodeDir}/remote-api-plugin/build-image/groovy/build.gradle[]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::{samplesCodeDir}/remote-api-plugin/build-image/kotlin/build.gradle.kts[]
----

==== Executing Functional Tests Against a Running Container

The following example code demonstrates how to build a Docker image from a Dockerfile, starts up a container for this image and exercises functional tests against the running container.
At the end of this operation, the container is stopped.

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::{samplesCodeDir}/remote-api-plugin/functional-test/groovy/build.gradle[]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::{samplesCodeDir}/remote-api-plugin/functional-test/kotlin/build.gradle.kts[]
----

==== Linking With Other Containers

In many situations your container does not start without dependencies like database.
In that case you may wish using traditional linking:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::{samplesCodeDir}/remote-api-plugin/linking-containers/groovy/build.gradle[]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::{samplesCodeDir}/remote-api-plugin/linking-containers/kotlin/build.gradle.kts[]
----