=== Extension

The plugin defines an extension with the namespace `javaApplication` as a child of the `docker` namespace. The following properties can be configured:

[options="header"]
|=======
|Property name   |Type        |Default value                                            |Description
|`baseImage`     |`String`    |`openjdk:jre-alpine`                                     |The Docker base image used for Java application.
|`exec`          |`Closure`   |Create ENTRYPOINT using script from Application plugin   |The ENTRYPOINT and/or CMD Dockerfile instructions
|`maintainer`    |`String`    |Value of `user.home` system property                     |The name and email address of the image maintainer (Deprecated).
|`port`          |`Integer`   |`8080`                                                   |The Docker image entry point port used for the Java application (Deprecated)
|`ports`         |`Integer[]` |`[]`                                                     |The Docker image exposed ports (if provided, this values will override `port` configuration property)
|`tag`           |`String`    |`<project.group>/<applicationName>:<project.version>`    |The tag used for the Docker image.
|=======

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::{samplesCodeDir}/application-plugin/basic/groovy/build.gradle[tags=extension]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::{samplesCodeDir}/application-plugin/basic/kotlin/build.gradle.kts[tags=extension]
----

==== Adding custom instructions to Dockerfile

The `exec` extension property accepts a Closure which delegates to the http://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.CompositeExecInstruction.html[Dockerfile.CompositeExecInstruction] subset of the http://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html[Dockerfile task].
It allows for specifying custom ENTRYPOINT or CMD commands at an appropriate location in the Dockerfile.

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::{samplesCodeDir}/application-plugin/basic/groovy/build.gradle[tags=exec]

----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::{samplesCodeDir}/application-plugin/basic/kotlin/build.gradle.kts[tags=exec]
----