=== Tasks

The plugin provides a set of tasks for your project and preconfigures them with sensible defaults.

[options="header"]
|=======
|Task name                 |Depends On                |Type                                                                                 |Description
|`dockerCopyDistResources` |`distTar`                 |http://www.gradle.org/docs/current/javadoc/org/gradle/api/tasks/Sync.html[Sync]      |Copies the resource files (like the Java application's TAR file) to a temporary directory for image creation.
|`dockerDistTar`           |`dockerCopyDistResources` |Dockerfile                                                                           |Creates the Docker image for the Java application.
|`dockerBuildImage`        |`dockerDistTar`           |DockerBuildImage                                                                     |Builds the Docker image for the Java application.
|`dockerPushImage`         |`dockerBuildImage`        |DockerPushImage                                                                      |Pushes created Docker image to the repository.
|=======

=== Examples

The following usage examples demonstrate code for common use cases.
More scenarios can be found in the https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPluginFunctionalTest.groovy[functional tests].

==== Using the Plugin for an Application Run on Jetty

.build.gradle
[source,groovy,subs="+attributes"]
----
apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'com.bmuschko.docker-java-application'

version = '1.0'
sourceCompatibility = 1.7

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.eclipse.jetty.aggregate:jetty-all:9.2.5.v20141112'
}

mainClassName = 'com.bmuschko.gradle.docker.application.JettyMain'

docker {
    javaApplication {
        maintainer = 'Jon Doe "jon.doe@gmail.com"'
    }
}
----

==== Additional Instructions in Dockerfile

You can add additional instructions to the dockerfile using `dockerDistTar` and http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html[Dockerfile task] DSL:

.build.gradle
[source,groovy,subs="+attributes"]
----
dockerDistTar {
    instruction {'RUN ls -la'}
    environmentVariable('JAVA_OPTS', '-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap')
}
----

will result in

----
FROM java
MAINTAINER user
ADD javaapp-1.0.0-SNAPSHOT.tar /
ENTRYPOINT ["/javaapp-1.0.0-SNAPSHOT/bin/javaapp"]
EXPOSE 8080
RUN ls -la
----

Or you can use form

.build.gradle
[source,groovy,subs="+attributes"]
----
dockerDistTar.instructionsFromTemplate file('Dockerfile.tmpl')
----