=== Tasks

The plugin provides a set of tasks for your project and preconfigures them with sensible defaults.

[options="header"]
|=======
|Task name                 |Depends On                |Type                                                                                 |Description
|`dockerSyncArchive`       |`assemble`                |http://www.gradle.org/docs/current/javadoc/org/gradle/api/tasks/Sync.html[Sync]      |Copies the Spring Boot archive to a temporary directory for image creation.
|`dockerCreateDockerfile`  |`bootJar` or `bootWar`    |Dockerfile                                                                           |Creates the Docker image for the Spring Boot application.
|`dockerBuildImage`        |`dockerCreateDockerfile`  |DockerBuildImage                                                                     |Builds the Docker image for the Spring Boot application.
|`dockerPushImage`         |`dockerBuildImage`        |DockerPushImage                                                                      |Pushes created Docker image to the repository.
|=======

=== Examples

The following usage examples demonstrate code for common use cases. More scenarios can be found in the https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplicationPluginFunctionalTest.groovy[functional tests].

==== Using the Plugin For an Application Run on Tomcat

.build.gradle
[source,groovy,subs="+attributes"]
----
plugins {
    id 'war'
    id 'org.springframework.boot' version '2.0.3.RELEASE'
    id 'io.spring.dependency-management' version '1.0.5.RELEASE'
    id 'com.bmuschko.docker-spring-boot-application'
}

version = '1.0'
sourceCompatibility = 8
targetCompatibility = 8

repositories {
    jcenter()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
    providedRuntime 'org.apache.tomcat.embed:tomcat-embed-jasper'
}

docker {
    springBootApplication {
        baseImage = 'openjdk:8-alpine'
    }
}
----