== About This Project

=== Contributing

Over the years, the plugin has tremendously grown in popularity.
Contributions from the community are very welcome.
To get started have a look at the https://github.com/bmuschko/gradle-docker-plugin/blob/master/.github/CONTRIBUTING.md[contribution guidelines].

==== Executing the Plugin's Test Suite With Custom Configuration

It is required to https://docs.docker.com/install/[install and run Docker Community Edition (CE)] on the machine running tests. Please refer to the installation manual for more information. The default setup can be configured with the help of the properties shown in the table below:

[options="header"]
|=======
|Description                 |System/Project/Environment variable          |Default Value
|Docker server URL           |dockerServerUrl/dockerServerUrl/DOCKER_HOST          |unix:///var/run/docker.sock
|Docker cert path            |dockerCertPath/dockerCertPath/DOCKER_CERT_PATH           |null
|Docker private registry URL |dockerPrivateRegistryUrl/dockerPrivateRegistryUrl/DOCKER_REGISTRY_HOST |http://localhost:5000
|=======

The following usage examples demonstrates running functional tests against the a Docker instance:

[source,shell]
----
./gradlew build functionalTest
----

OR

[source,shell]
----
./gradlew build functionalTest -PdockerServerUrl=unix:///var/run/docker.sock
----

OR

[source,shell]
----
./gradlew build functionalTest -DdockerServerUrl=unix:///var/run/docker.sock
----

OR

[source,shell]
----
export DOCKER_HOST=unix:///var/run/docker.sock && ./gradlew build functionalTest
----

OR

[source,shell]
----
./gradlew build functionalTest -PdockerServerUrl=http://192.168.59.103:2376
----

=== Maintainers

* https://github.com/cdancy[Christopher Dancy]
* https://github.com/bmuschko[Benjamin Muschko]
* https://github.com/orzeh[Orzeh]