#!/bin/bash

if [[ $1 == "get" ]]; then
    read > /dev/null

    echo '{' \
         '  "ServerURL": "url",' \
         '  "Username": "username",' \
         '  "Secret": "secret"' \
         '}'
elif [[ $1 == "list" ]]; then
    echo '{' \
         '  "url": "username"' \
         '}'
else
    exit 1
fi
