#!/bin/bash

if [[ $1 == "get" ]]; then
    read > /dev/null

    echo '{"ServerURL":"https://index.docker.io/v1/","Username":"mac_user","Secret":"XXX"}'
elif [[ $1 == "list" ]]; then
    echo '{"https://index.docker.io/v1/": "mac_user"}'
else
    exit 1
fi
